// <auto-generated />
using ApiCadastrarVeiculo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCadastrarVeiculo.Migrations
{
    [DbContext(typeof(VeiculoContext))]
    [Migration("20250606224746_CriarTabelaVeiculos")]
    partial class CriarTabelaVeiculos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ApiCadastrarVeiculo.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chassis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chassis = "9BWZZZ377VT004251",
                            Cor = "Prata",
                            Marca = "Chevrolet",
                            Modelo = "Onix",
                            Placa = "ABC1234",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 2,
                            Chassis = "1HGCM82633A123456",
                            Cor = "Preto",
                            Marca = "Honda",
                            Modelo = "Civic",
                            Placa = "DEF5678",
                            Status = "Recuperado"
                        },
                        new
                        {
                            Id = 3,
                            Chassis = "3FAFP31394R128765",
                            Cor = "Branco",
                            Marca = "Volkswagen",
                            Modelo = "Gol",
                            Placa = "GHI9012",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 4,
                            Chassis = "JH4DA9350MS012345",
                            Cor = "Azul",
                            Marca = "Ford",
                            Modelo = "Fiesta",
                            Placa = "JKL3456",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 5,
                            Chassis = "2C4RC1BG2HR567890",
                            Cor = "Vermelho",
                            Marca = "Hyundai",
                            Modelo = "HB20",
                            Placa = "MNO7890",
                            Status = "Recuperado"
                        },
                        new
                        {
                            Id = 6,
                            Chassis = "3N1AB7APXGY345678",
                            Cor = "Cinza",
                            Marca = "Ford",
                            Modelo = "Ka",
                            Placa = "PQR1234",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 7,
                            Chassis = "KL1TD56607B765432",
                            Cor = "Preto",
                            Marca = "Fiat",
                            Modelo = "Palio",
                            Placa = "STU5678",
                            Status = "Recuperado"
                        },
                        new
                        {
                            Id = 8,
                            Chassis = "1FTRX17W1XKA98765",
                            Cor = "Branco",
                            Marca = "Toyota",
                            Modelo = "Corolla",
                            Placa = "VWX9012",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 9,
                            Chassis = "JN8AS5MT2DW123456",
                            Cor = "Azul",
                            Marca = "Chevrolet",
                            Modelo = "Cruze",
                            Placa = "YZA3456",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 11,
                            Chassis = "WVWZZZ1KZAW056789",
                            Cor = "Prata",
                            Marca = "Ford",
                            Modelo = "EcoSport",
                            Placa = "EFG1122",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 12,
                            Chassis = "ZFAAXX00A0P012345",
                            Cor = "Cinza",
                            Marca = "Fiat",
                            Modelo = "Toro",
                            Placa = "HIJ3344",
                            Status = "Recuperado"
                        },
                        new
                        {
                            Id = 13,
                            Chassis = "MAJ6S3GL8LC987654",
                            Cor = "Vermelho",
                            Marca = "Fiat",
                            Modelo = "Strada",
                            Placa = "KLM5566",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 14,
                            Chassis = "5NPE24AF8FH456321",
                            Cor = "Azul",
                            Marca = "Chevrolet",
                            Modelo = "Celta",
                            Placa = "NOP7788",
                            Status = "Recuperado"
                        },
                        new
                        {
                            Id = 15,
                            Chassis = "1FAFP55U61A432109",
                            Cor = "Amarelo",
                            Marca = "Volkswagen",
                            Modelo = "Fusca",
                            Placa = "QRS9900",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 16,
                            Chassis = "VF1RFA00458012345",
                            Cor = "Branco",
                            Marca = "Renault",
                            Modelo = "Logan",
                            Placa = "TUV1133",
                            Status = "Recuperado"
                        },
                        new
                        {
                            Id = 17,
                            Chassis = "9C2JC41104R000123",
                            Cor = "Preto",
                            Marca = "Renault",
                            Modelo = "Duster",
                            Placa = "WXY4455",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 18,
                            Chassis = "4T1BF1FK2GU789321",
                            Cor = "Cinza",
                            Marca = "Toyota",
                            Modelo = "Etios",
                            Placa = "ZAB6677",
                            Status = "Recuperado"
                        },
                        new
                        {
                            Id = 19,
                            Chassis = "KMHD84LF6JU007700",
                            Cor = "Prata",
                            Marca = "Nissan",
                            Modelo = "March",
                            Placa = "CDE8899",
                            Status = "Roubado"
                        },
                        new
                        {
                            Id = 20,
                            Chassis = "KNADM4A38F6021345",
                            Cor = "Azul",
                            Marca = "Nissan",
                            Modelo = "Versa",
                            Placa = "FGH0001",
                            Status = "Recuperado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
